# Site settings
title: Wlonkery
email: kit@transneptune.net
description: > # this means to ignore newlines until "baseurl:"
  I may put some game things here maybe?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wlonk.github.io"
twitter_username: wlonk
github_username:  wlonk

# Build settings
markdown: kramdown
